context:
  version: "1.2.0"

package:
  name: doggo
  version: ${{ version }}

source:
  url: https://github.com/mr-karan/doggo/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ddea7da5f8e6263626ffbff57e3df5e84df4343a740b2f7a8dae2505aae645d9
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save ./cmd/doggo --save_path ../library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/doggo -ldflags="-s -w" ./cmd/doggo
      else: go build -v -o %LIBRARY_BIN%\doggo.exe -ldflags="-s" .\cmd\doggo

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: doggo --help
  - package_contents:
      bin:
        - doggo
      strict: true

about:
  homepage: https://github.com/mr-karan/doggo
  summary: 🐶 Command-line DNS Client for Humans.
  description: |
    doggo is a modern command-line DNS client (like dig) written in Golang. It outputs information in a neat concise manner and supports protocols like DoH, DoT, DoQ, and DNSCrypt as well.
  license: GPL-3.0-or-later
  license_file:
    - src/LICENSE
    - library_licenses/
  documentation: https://pkg.go.dev/github.com/mr-karan/doggo
  repository: https://github.com/mr-karan/doggo

extra:
  recipe-maintainers:
    - pavelzw
